### PR TITLE
Update PageResource.php

### PR DESCRIPTION
**Pull request by kikoseijo**
Replaced names for translation purposes.

### CODE REVIEW

**Comment by kikoseijo** [comment]
If you could release, we could benefit from translating the menu, and so.

thanks.

**Comment by remipou** [comment]
thanks @kikoseijo

**Comment by remipou** [comment]
1.0.3 on packagist. you're welcome to commit new PR for the menus. i'll do it otherwise. @kikoseijo

**Comment by kikoseijo** [comment]
Yes, its updated local but didn't happened to change.
Not sure why, if you could make it work @remipou because im lost.

**Pull request merged**
